# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: getid.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'getid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgetid.proto\x12\x05getid\"\x0b\n\tIDRequest\"\x1a\n\x07IDReply\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x0bInformation\x12/\n\tRequestID\x12\x10.getid.IDRequest\x1a\x0e.getid.IDReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'getid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDREQUEST']._serialized_start=22
  _globals['_IDREQUEST']._serialized_end=33
  _globals['_IDREPLY']._serialized_start=35
  _globals['_IDREPLY']._serialized_end=61
  _globals['_INFORMATION']._serialized_start=63
  _globals['_INFORMATION']._serialized_end=125
# @@protoc_insertion_point(module_scope)
